[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
primaryColor = "#00A0C8"
backgroundColor = "#002147"
secondaryBackgroundColor = "#373A36"
textColor = "#EBEEEE"
font = "sans-serif"
